image: docker:stable

stages:
  - build
  - test


build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - cd app
    - docker login -u 12211479verdozagerman -p 4685GitLab https://gitlab.com/12211479verdozagerman/test-django-docker
    - docker pull registry.gitlab.com/12211479verdozagerman/test-django-dockerlatest || true
    - docker build
        --cache-from registry.gitlab.com/12211479verdozagerman/test-django-docker:latest
        --tag registry.gitlab.com/12211479verdozagerman/test-django-docker:latest
        --file ./Dockerfile
        "."
    - docker push registry.gitlab.com/12211479verdozagerman/test-django-docker:latest

test:
  stage: test
  image: registry.gitlab.com/12211479verdozagerman/test-django-docker:latest
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: users
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: runner
    DATABASE_TEST_URL: postgres://runner:runner@postgres:5432/users
  script:
    - cd app
    - pytest -p no:warnings --cov=.
    - flake8 .
    - black --check --exclude="migrations|venv" .
    - isort ./*/*.py --check-only