version: '3.7'

services:
  movies:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:home/germanvglz/django-tdd-docker/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
